// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://fsazmxgylfrwwgmvluyg.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZzYXpteGd5bGZyd3dnbXZsdXlnIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDU4NDUxNjYsImV4cCI6MjA2MTQyMTE2Nn0.TIHs_f9vUc3agVBlKcyjqT0yoCiD7ZYDFoVX372VFGc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);